<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto

namespace Grpc\Php\Telpo;

/**
 * Protobuf type <code>grpc.php.telpo.hi</code>
 */
interface hiInterface
{
    /**
     * Method <code>sayHello</code>
     *
     * @param \Grpc\Php\Telpo\HiUser $request
     * @return \Grpc\Php\Telpo\HiReply
     */
    public function sayHello(\Grpc\Php\Telpo\HiUser $request);

    /**
     * Method <code>sayHello1</code>
     *
     * @param \Grpc\Php\Telpo\HiUser $request
     * @return \Grpc\Php\Telpo\HiReply
     */
    public function sayHello1(\Grpc\Php\Telpo\HiUser $request);

    /**
     * Method <code>sayHello2</code>
     *
     * @param \Grpc\Php\Telpo\HiUser $request
     * @return \Grpc\Php\Telpo\HiReply
     */
    public function sayHello2(\Grpc\Php\Telpo\HiUser $request);

    /**
     * Method <code>hello</code>
     *
     * @param \Grpc\Php\Telpo\helloReq $request
     * @return \Grpc\Php\Telpo\HiReply
     */
    public function hello(\Grpc\Php\Telpo\helloReq $request);

}

